### ISSUE TITLE
[BUG] Reordering while importing messes up dictionary list

### ISSUE THREAD

**Issue by iamllama** [yomidevs/yomitan#1566] opened 2024-11-05 04:46 UTC
**Description**

I reordered my dictionaries while importing 三省堂国語辞典 (was at step 8/8 iirc, race condition maybe), and somehow my list ended up duplicated like this:

![image](https://github.com/user-attachments/assets/66d993e3-ee15-45e7-ae6c-f7287d5d9028)

Deleting one of the JPDBs resulted in:

![image](https://github.com/user-attachments/assets/bcb949d4-c5ad-4c3b-9c2d-4e9793958780)

**Browser version**
Firefox 133

**Yomitan version**
24.10.7.1

**Comment by MarvNC** [comment] 2024-11-05 04:55
Does it stay messed up after restarting the extension/your browser? I think I've seen this bug before but it didn't leave any lasting damage.

**Comment by iamllama** [comment] 2024-11-05 04:57
It fixed itself after I removed a dict, didn't get an opportunity to check if restarting or disabling would've fixed it :/

**Comment by Kuuuube** [comment] 2024-11-05 23:36
Just refreshing the page should fix this.

**Comment by iamllama** [comment] 2024-11-06 08:05
> Just refreshing the page should fix this.

Came across it again (en/disabling instead of reordering) and refreshing did fix it 😅

**Comment by khaitruong922** [comment] 2024-11-06 13:39
tried to reorder the dictionaries while importing but cannot reproduce this issue

**Comment by Kuuuube** [comment] 2024-11-23 15:45
Closing this as it is not really fixable due to how we have to handle settings to not break things across browsers.

Also possibly related to #957.

**Closed by Kuuuube** 2024-11-23 15:45 UTC
Labels: kind/bug
